### ISSUE TITLE
Will not install in VS 2017 Enterprise.

### ISSUE THREAD

**Issue by streamtree** [akaStiX/ProgressiveScrollVS2017#2]
Running 15.6 version of VS 2017 Enterprise. Will not install:

3/7/2018 1:02:46 PM - The extension with ID 'ProgressiveScrollVS2017..1b4c078b-4b80-4cf3-80af-44b9088f8d8f' is not installed to Microsoft Visual Studio Enterprise 2017.
3/7/2018 1:02:47 PM - Extension cannot be installed to the following products due to missing prerequisites:
3/7/2018 1:02:47 PM - 	Microsoft Visual Studio Enterprise 2017
3/7/2018 1:02:47 PM - 		-------------------------------------------------------
3/7/2018 1:02:47 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
3/7/2018 1:02:47 PM - 		Name         : Visual Studio core editor
3/7/2018 1:02:47 PM - 		Version      : [15.0]
3/7/2018 1:02:47 PM - 		Error        : The prerequisite version specified does not match the version installed
3/7/2018 1:02:47 PM - 
3/7/2018 1:02:47 PM - System.InvalidOperationException: No modifications could be applied.
   at VSIXInstaller.MultipleChangePage..ctor(ExtensionData data)
   at VSIXInstaller.LoadingPage.<>c__DisplayClass11_1.<OnLoaded>b__2()

**Comment by cry-inc** [comment]
I had exactly the same problem with Visual Studio Professional 15.6.

A quick hack that worked for me was to check out the sources and edit the file source.extension.vsixmanifest. I used [15.6] instead of [15.0] as prerequisite version for the Microsoft.VisualStudio.Component.CoreEditor.

**Comment by akaStiX** [comment]
It's fixed in 0.9.1
